spring:
  application:
    name: hhplus
  profiles:
    active: local
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
  flyway:
    enabled: true
  data:
    redis:
      timeout: 3000ms

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: hhplus_user
    password: hhplus_user
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000
      max-lifetime: 60000
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: concert-reservation-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "kr.hhplus.be.server.*"

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type: WARN
    kr.hhplus.be.server.application.scheduler: INFO

app:
  queue:
    max-active-users: 100
    token-ttl-minutes: 10
    scheduler:
      enabled: true
      process-interval-ms: 1000
  scheduler:
    cleanup:
      enabled: true
      interval-ms: 60000

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094  # 클러스터로 변경
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: concert-reservation-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "kr.hhplus.be.server.*"

app:
  queue:
    max-active-users: 10
    token-ttl-minutes: 1
    scheduler:
      enabled: false
      process-interval-ms: 5000
  scheduler:
    cleanup:
      enabled: false
      interval-ms: 300000
  payment:
    use-conditional-update: false